version: '3'

services:
  redis:
    image: redis:7.2.0
    ports:
      - '6379:6379'
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: pix
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - mongodbdata:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8881:8881'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
volumes:
  mongodbdata:
networks:
  net:
    driver: bridge